datacarpentry/spreadsheets-socialsci

_episodes/01-creating-tables.md
_episodes/02-reformatting.md
_episodes/03-formatting-problems.md
_episodes/04-dates.md
_episodes/05-quality-control.md
_episodes/06-exporting-data.md

Updates the objectives, key points and questions for each episode. In many cases, I've copied these from the analogous episode in the Ecology spreadsheets lesson, but not always. There is some new material in this lesson and also some material in the Ecology lesson that is not covered here. I've adjusted the objectives, etc, as needed in those situations.
Also some general formatting fixes.

update episode outlines

---

setup.md

Fixes https://github.com/datacarpentry/spreadsheets-socialsci/issues/42

remove mention of openoffice in setup

---

_episodes/01-format-data.md

Fixes https://github.com/datacarpentry/spreadsheets-socialsci/issues/47

Add mention of data organization paper

---

_episodes/01-format-data.md

Put references in a callout box so they stand out from the lesson text.

move references to callout box

---

_episodes/00-intro.md

There is a word missing in this sentence, and I am not sure what word to use, but it seems like difficult or hard fits.
Please delete the text below before submitting your contribution. 
---

word missing in sentence

---

_episodes/01-format-data.md
_episodes/03-dates-as-data.md
_extras/guide.md
setup.md

**I've made the following changes based on feedback documented in the following Issues:**
Updates to metadata section in Episode 01 to include discussion of standards and codebooks - #48, #66, #67
Non-english versions of Excel - note added to instructor notes - #65
Issues with opening the correct spreadsheet tab - note added to instructor notes - #64
Issues with Apple Numbers - notes added to `setup.md` and instructor notes - #63
Issues with LibreOffice - notes added to Episode 01 and instructor notes about importing with semicolons tagged as separators - #62

Updates for Social Science training milestone

---

setup.md

removed some redundant language on line 21 ("To learn more about the data, For more information about the dataset ...")

Correct typo in setup.md

---

_episodes/03-dates-as-data.md

"a research from the US" --> "a researcher from the US"

correct typo in line 71

---

_episodes/04-quality-assurance.md

"and entry like" --> "an entry like"

fix typo on line 49

---

_episodes/04-quality-assurance.md

"wall_type" --> "respondent_wall_type" to match the example data file

correcting variable name in line 101

---

README.md
_extras/guide.md

Hi Christopher
I hope I have done this right! 
I have amended the README file to include information about the datasets included in the lesson to model good data management practice to students on the course (i.e. provide documentation accompanying the datasets). Would it be possible to make this version of the README file available alongside the data files available for download in the setup of the lesson? 
All the best
Alison 
---

Changes to Readme file

---

_episodes/03-dates-as-data.md

Changed the "it's" to "its" as noted in [Issue 99](https://github.com/datacarpentry/spreadsheets-socialsci/issues/99). Thanks!

Edited 03-dates-as-data.md to address Issue 99

---

_episodes/04-quality-assurance.md

Creating the list entries did not work with commas or spaces but rather semicolons in Office 365

Updated restricting data entries from a list

---

_episodes/03-dates-as-data.md

It was written as 'compatability', so I suggest to correct it to 'compatibility'.
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to …

Correction of typo, 'compatibility'

---

_episodes/04-quality-assurance.md

There is a way to display circles around cells that don't adhere to the data validation checks in Excel (See the [Excel documentation](https://support.microsoft.com/en-us/office/display-or-hide-circles-around-invalid-data-69144e43-fc71-48e0-8d4f-0b9f1ea96c03#:~:text=On%20the%20Data%20tab%2C%20in,cells%20that%20contain%20invalid%20data.) )

Add info about circle invalid data to episode 4

---

setup.md

Include Onlyoffice and WPS office as spreadsheet programs. Add links for these as well.

Add links to possible other spreadsheet programs

---

_extras/guide.md

"Quality assurance" was not aligned properly.
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …

Update guide.md (format fix for one of the titles)

---

_episodes/03-dates-as-data.md

Editing filename in episode 03 for consistency and clarity

---

_episodes/02-common-mistakes.md

Fixing bad URL for issue #137.

Fix 'Nine simple ways...' link for issue #137

---

_extras/guide.md

Add speakers note that was removed from Episode 01 to Instructor Notes

---

_episodes/02-common-mistakes.md

This should resolve pull request #117

Add clarifying note about multiple tabs to episode 3, re: #117

---

_episodes/02-common-mistakes.md

Replace null values screenshot with markdown table

---

_episodes/00-intro.md

This will address https://github.com/carpentries/lesson-transition/issues/48

fix missing block quote symbol

---

episodes/01-format-data.md
episodes/02-common-mistakes.md
episodes/03-dates-as-data.md
episodes/05-exporting-data.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #170
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Fixing typos and wording. 
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
Fixing typos and wording on episode files 1, 2, 3, 5. All 14 points raised by @NoaYaari were addresses, except point 11, which was already mentioned and solved in #160.
</details>

Closes #170. Fixing typos and wording

---

episodes/03-dates-as-data.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
After merging #175 today, I just realized there is a missing line break
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be …

Fix missing line break when merging PR #175

---

.gitignore
episodes/00-intro.md
episodes/01-format-data.md
episodes/02-common-mistakes.md
episodes/03-dates-as-data.md
learners/setup.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #73, #110, #122, #124, #168, #174
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
This PR includes multiple updates on episodes 1, 2, 3, and 4. The changes are made to address issues raised by the community.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may …

Milestone "Working on introduction issues" updates
